"""SQLAlchemy Core 테이블 메타데이터 — init_db.py 스키마와 일치"""

from sqlalchemy import (
    MetaData, Table, Column,
    Integer, Text, Float, Boolean,
)

metadata = MetaData()

teams = Table(
    "teams", metadata,
    Column("id", Integer, primary_key=True),
    Column("name", Text, nullable=False),
    Column("short_name", Text, nullable=False),
    Column("city", Text, nullable=False),
    Column("stadium", Text, nullable=False),
    Column("logo_initial", Text, nullable=False),
)

players = Table(
    "players", metadata,
    Column("id", Integer, primary_key=True),
    Column("name", Text, nullable=False),
    Column("team_id", Integer),
    Column("position", Text, nullable=False),
    Column("position_detail", Text),
    Column("back_number", Integer),
    Column("birth_date", Text),
    Column("height", Integer),
    Column("weight", Integer),
    Column("bat_hand", Text),
    Column("throw_hand", Text),
    Column("is_active", Boolean),
)

games = Table(
    "games", metadata,
    Column("id", Integer, primary_key=True),
    Column("date", Text, nullable=False),
    Column("time", Text),
    Column("stadium", Text),
    Column("home_team_id", Integer),
    Column("away_team_id", Integer),
    Column("home_score", Integer),
    Column("away_score", Integer),
    Column("status", Text),
    Column("day_of_week", Text),
    Column("is_night_game", Boolean),
)

batter_stats = Table(
    "batter_stats", metadata,
    Column("id", Integer, primary_key=True),
    Column("game_id", Integer),
    Column("player_id", Integer),
    Column("team_id", Integer),
    Column("pa", Integer),
    Column("ab", Integer),
    Column("hits", Integer),
    Column("doubles", Integer),
    Column("triples", Integer),
    Column("hr", Integer),
    Column("rbi", Integer),
    Column("runs", Integer),
    Column("sb", Integer),
    Column("cs", Integer),
    Column("bb", Integer),
    Column("hbp", Integer),
    Column("so", Integer),
    Column("gdp", Integer),
    Column("sf", Integer),
    Column("ibb", Integer),
    Column("runners_on_scoring", Boolean),
    Column("opponent_pitcher_hand", Text),
    Column("inning", Integer),
    Column("is_home", Boolean),
    Column("score_diff", Integer),
)

pitcher_stats = Table(
    "pitcher_stats", metadata,
    Column("id", Integer, primary_key=True),
    Column("game_id", Integer),
    Column("player_id", Integer),
    Column("team_id", Integer),
    Column("ip_outs", Integer),
    Column("hits_allowed", Integer),
    Column("hr_allowed", Integer),
    Column("bb_allowed", Integer),
    Column("hbp_allowed", Integer),
    Column("so_count", Integer),
    Column("runs_allowed", Integer),
    Column("er", Integer),
    Column("is_starter", Boolean),
    Column("decision", Text),
    Column("batter_hand", Text),
    Column("is_home", Boolean),
)

batter_season = Table(
    "batter_season", metadata,
    Column("id", Integer, primary_key=True),
    Column("player_id", Integer),
    Column("season", Integer, nullable=False),
    Column("team_id", Integer),
    Column("games", Integer),
    Column("pa", Integer),
    Column("ab", Integer),
    Column("hits", Integer),
    Column("doubles", Integer),
    Column("triples", Integer),
    Column("hr", Integer),
    Column("rbi", Integer),
    Column("runs", Integer),
    Column("sb", Integer),
    Column("cs", Integer),
    Column("bb", Integer),
    Column("hbp", Integer),
    Column("so", Integer),
    Column("gdp", Integer),
    Column("sf", Integer),
    Column("ibb", Integer),
    Column("avg", Float),
    Column("obp", Float),
    Column("slg", Float),
    Column("ops", Float),
    Column("woba", Float),
    Column("wrc_plus", Float),
    Column("war", Float),
    Column("babip", Float),
    Column("iso", Float),
    Column("bb_pct", Float),
    Column("k_pct", Float),
    Column("ops_vs_lhp", Float),
    Column("ops_vs_rhp", Float),
    Column("ops_risp", Float),
    Column("ops_home", Float),
    Column("ops_away", Float),
)

pitcher_season = Table(
    "pitcher_season", metadata,
    Column("id", Integer, primary_key=True),
    Column("player_id", Integer),
    Column("season", Integer, nullable=False),
    Column("team_id", Integer),
    Column("games", Integer),
    Column("wins", Integer),
    Column("losses", Integer),
    Column("saves", Integer),
    Column("holds", Integer),
    Column("ip_outs", Integer),
    Column("hits_allowed", Integer),
    Column("hr_allowed", Integer),
    Column("bb_allowed", Integer),
    Column("hbp_allowed", Integer),
    Column("so_count", Integer),
    Column("runs_allowed", Integer),
    Column("er", Integer),
    Column("era", Float),
    Column("whip", Float),
    Column("fip", Float),
    Column("xfip", Float),
    Column("war", Float),
    Column("babip", Float),
    Column("lob_pct", Float),
    Column("k_per_9", Float),
    Column("bb_per_9", Float),
    Column("hr_per_9", Float),
    Column("k_bb_ratio", Float),
    Column("is_starter", Boolean),
)

league_constants = Table(
    "league_constants", metadata,
    Column("season", Integer, primary_key=True),
    Column("woba_scale", Float),
    Column("league_woba", Float),
    Column("league_wrc", Float),
    Column("fip_constant", Float),
    Column("league_hr_fb_rate", Float),
    Column("rppa", Float),
    Column("league_rpw", Float),
)
